### ISSUE TITLE
example configuration json

### ISSUE THREAD

**Issue by wanghaisheng** [edward-zhu/umaru#1]
```
➜ /Users/wanghaisheng/workspace/toch-ocr-umaru git:(master) ✗>th main.lua -setting setting.json
/Users/wanghaisheng/torch/install/bin/luajit: .../wanghaisheng/torch/install/share/lua/5.1/trepl/init.lua:383: .../wanghaisheng/torch/install/share/lua/5.1/torch/init.lua:102: class nn.GRU has been already assigned a parent class

stack traceback:
    [C]: in function 'error'
    .../wanghaisheng/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
    main.lua:3: in main chunk
    [C]: in function 'dofile'
    ...heng/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x010547dbb0
```

**Comment by edward-zhu** [comment]
The error is caused by the newly-shipped official GRU implementation which overlapped my impl. The simplest way to fix that is to comment out the 3rd line of main.lua.

**Comment by wanghaisheng** [comment]
@edward-zhu 
another error 

```
[0.0020][0.0005]Loading samples...
/Users/wanghaisheng/torch/install/bin/luajit: ./loader.lua:98: attempt to compare nil with number
stack traceback:
    ./loader.lua:98: in function 'load'
    main.lua:131: in main chunk
    [C]: in function 'dofile'
    ...heng/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x010724abb0
```

**Comment by edward-zhu** [comment]
I think it’s because the filename in your training list file is invalid.

发件人:  wanghaisheng notifications@github.com
答复:  edward-zhu/umaru reply@reply.github.com
日期:  2016年1月10日 星期日 下午9:42
至:  edward-zhu/umaru umaru@noreply.github.com
抄送:  Edward Zhu edward_zhu@bupt.edu.cn
主题:  Re: [umaru] example configuration json (#1)

another error 
[0.0020][0.0005]Loading samples...
/Users/wanghaisheng/torch/install/bin/luajit: ./loader.lua:98: attempt to compare nil with number
stack traceback:
    ./loader.lua:98: in function 'load'
    main.lua:131: in main chunk
    [C]: in function 'dofile'
    ...heng/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x010724abb0

**Comment by wanghaisheng** [comment]
what kind of file should i use  ?
i just  change the filename  to full-train.txt
https://raw.githubusercontent.com/phunterlau/wangfeng-rnn/master/input.txt

**Comment by edward-zhu** [comment]
This program is to train a model using training samples, a .png and a .gt.txt pair, with the png file is the image of a text line and the .gt.txt is its ground truth in UTF-8 codec.

So you need to prepare some of them, and put paths of all the png file to the training file list (in this case your full-train.txt).

发件人:  wanghaisheng notifications@github.com
答复:  edward-zhu/umaru reply@reply.github.com
日期:  2016年1月10日 星期日 下午10:13
至:  edward-zhu/umaru umaru@noreply.github.com
抄送:  Edward Zhu edward_zhu@bupt.edu.cn
主题:  Re: [umaru] example configuration json (#1)

what kind of file should i use  ?
i just  change the filename  to full-train.txt
https://raw.githubusercontent.com/phunterlau/wangfeng-rnn/master/input.txt

**Comment by wanghaisheng** [comment]
could you provide a few examples you used?

**Comment by wanghaisheng** [comment]
does file like this  works?
https://github.com/tmbdev/ocropy/blob/master/tests/1241-010032.png
https://github.com/tmbdev/ocropy/blob/master/tests/1241-010032.gt.txt
what is the format of  full-train.txt?
let`s say i have 10 pair of the above files

**Comment by edward-zhu** [comment]
That’s fine.

Normally, you might need thousands of such kind of samples to get an acceptable model.

Put all the paths of the 10 png files in full-train.txt, for example:

Samples/1.png
Samples/2.png
…
Samples/10.png

It could be absolute path or relative path against the folder of main.lua.

发件人:  wanghaisheng notifications@github.com
答复:  edward-zhu/umaru reply@reply.github.com
日期:  2016年1月10日 星期日 下午11:11
至:  edward-zhu/umaru umaru@noreply.github.com
抄送:  Edward Zhu edward_zhu@bupt.edu.cn
主题:  Re: [umaru] example configuration json (#1)

does file like this  works?
https://github.com/tmbdev/ocropy/blob/master/tests/1241-010032.png
https://github.com/tmbdev/ocropy/blob/master/tests/1241-010032.gt.txt
what is the format of  full-train.txt?
let`s say i have 10 pair of the above files

**Comment by wanghaisheng** [comment]
thx
